---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: aryangupta4460/webapp
        imagePullPolicy: Always
        name: webapp

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 8443
  selector:
    app: webapp
  type: NodePort
